### ISSUE TITLE
Compatibility 4.0

### ISSUE THREAD

**Issue by bebeGit** [ThatCompany/that_email_log#2]
Are there any plans to accomplish the compatibility for redmine vers. 4.0.x ? Thanks in andvance!

**Comment by drexlma** [comment]
need! :D

**Comment by s-andy** [comment]
Yes, this is planned. Can't tell when exactly, though.

**Comment by TrumanRu** [comment]
Vote for this issue.

**Comment by tomaskrejzek** [comment]
Vote for this issue too. It would be perfect when can use it.

Thank you very much, Tom

**Comment by s-andy** [comment]
The plugin has been ported to Redmine 4.0. Sorry, that it took so long.
