### ISSUE TITLE
Compatibility 4.1

### ISSUE THREAD

**Issue by MasyGreen** [ThatCompany/that_email_log#3]
![image](https://user-images.githubusercontent.com/17898601/72417589-40c6b400-378a-11ea-8429-a55484dab9fd.png)

**Comment by Koubiacz** [comment]
Hi,
I have the same problem with a fresh Redmine 4.1 installation.

Regards

**Comment by DolezalDavid** [comment]
+1. This is very useful plugin and I will be very happy if somebody make new version compatibility with 4.xx

**Comment by 0geronimo0** [comment]
+1. Great plugin. I would like to have it in 4.1.1

**Comment by TyRoden** [comment]
We are working on migrating it up to 4.x compatibility, it is still
underway.

**Comment by kallenp** [comment]
Hello. Please, what is the actual state about Redmine 4.1 compatibility ?

**Comment by TyRoden** [comment]
Not yet compatible,  but it is actively being developed

**Comment by kallenp** [comment]
Hi, please, are there any news about 4.1 compatibility ?

**Comment by MasyGreen** [comment]
Actual Compatible with Redmine 4.2.x )

**Comment by kallenp** [comment]
> Actual Compatible with Redmine 4.2.x )

It's perfect ! :-) 
And is it compatible with Redmine 4.x too or only with 4.2.x ?

**Comment by MasyGreen** [comment]
Now it work!!! Great job!!! 4.1.2.stable.20964

**Comment by s-andy** [comment]
FYI: Support for Redmine 4.1 and 4.2 was added only now.
It worked, but there were issues, which were fixed now.
